name: Dramatic
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  extractor:
    git:
      url: https://github.com/Toasty360/DramaExtractor.git
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  html: ^0.15.4
  flutter_launcher_icons: ^0.13.1
  carousel_slider: ^4.2.1
  media_kit:
  media_kit_video:
  media_kit_libs_video:
  extended_image: ^8.2.0
  toast: ^0.3.0
  hive:
  hive_flutter:
  path_provider: ^2.1.2
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:

  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/images/logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/girl.png
    - assets/images/pfp.jpg
