name: Dramatic
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  html: ^0.15.4
  flutter_launcher_icons: ^0.13.1
  carousel_slider: ^4.2.1
  media_kit:
  media_kit_video: ^1.2.4
  media_kit_libs_video:
  extended_image: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/images/logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/girl.png
    - assets/images/pfp.jpg
